# check whether python is installed
# run an array of install for requirmeents.txt in coord-transform & render-form

venv:
	python3 -m venv venv

install:
	pip install -r requirements.txt
	pip install -r coord-transform/requirements.txt 
	pip install -r render-form/requirements.txt
