# check whether python is installed
# run an array of install for requirmeents.txt in coord-transform & render-form

venv:
	python3 -m venv venv

install:
	pip install -r requirements.txt
	pip install -r src/coord_transform/requirements.txt 
	pip install -r src/render_form/requirements.txt

install-examples:
	pip install -r src/examples/flow_field_visual/requirements.txt